### ISSUE TITLE
Strange crash with Atomicstryker mods

### ISSUE THREAD

**Issue by Staegrin** [Qmunity/BluePower#245]
I updated to the latest BluePower version and created a fresh testworld. After setting up a sorting/oreprocessing system from scratch and letting it run everything works fine.

In the past I couldn't update past version 1.751 of bluepower because the world would crash to the main screen if any tubes were in the world. Any worlds without tubes were accessible, but as soon as tubes were placed and the map was closed. If it was reopened it would crash as well.

In the past there was never a clear culprit besides the updated version of bluepower. There would be no crashlog only the on-screen message that a fatal error had occurred and the map had to be closed.

This time the console named the culprit as BluePower and atomicstryker's updatchecker/ruins mod.
After removing the ruins mod but not any other mods by atmicstryker the map started up without any problems.

Console log:
http://pastebin.com/JgA8eJaK
Crash log:
http://pastebin.com/shvb90mW
FML log:
https://gist.github.com/Staegrin/aa6ea8d535a13dea5c69

Hope this helps. In the future I won't use the ruins mod but similar errors might happen again so I thought I should share this.

**Comment by amadornes** [comment]
Well, your issues with the old versions of BluePower are really weird. Why didn't you report it at the time? It probably wasn't a BluePower bug, as everybody else was able to open their worlds perfectly so it was most surely caused by another mod in your pack.

The bug in the "console log" has already been fixed, the "crash log" doesn't have anything to do with BluePower and the FML log... well, that one wasn't really needed, but thanks anyways :P
