### ISSUE TITLE
Pneumatic tube visual bug

### ISSUE THREAD

**Issue by nikita488** [Qmunity/BluePower#255]
This bug happens when through tubes quickly pass items. Then this bug disappears. Sorry for my bad English :)
![2015-01-10_13 29 33](https://cloud.githubusercontent.com/assets/6237881/5691235/c4a00a4a-98cc-11e4-9f55-1f3686dc5d6d.png)
![2015-01-10_13 29 37](https://cloud.githubusercontent.com/assets/6237881/5691236/c4a38c9c-98cc-11e4-9b99-43215a2c28cd.png)

**Comment by amadornes** [comment]
I'm not really sure what you're saying the issue is. I've looked at both pictures and the first one has a block of stone travelling through the pipe, and it's colored blue.
If you mean that the item stops in a junction (where more than one pipe crosses), that's lag, but not a bug :P
Some more info would be appreciated ;)
Oh, and don't worry if your English is bad because mine is too and I still answer most of the bug reports xD

**Comment by nikita488** [comment]
Hmm, I can't understand this lag or bug :D Yes, item stops in a junction and disappears after a few seconds.

**Comment by nikita488** [comment]
I changed the tube on the magnetic tube, change the color of the pipes, 1 red, 2 green, 3 blue, and I do not think that this lag is because in the third chest (which is connected to the pipe painted in blue) is 64 stone, and in the pipe is still one stone, which disappears after a few seconds.
![2015-01-10_14 43 13](https://cloud.githubusercontent.com/assets/6237881/5691440/6f2397e8-98d7-11e4-8da4-3c48a0171663.png)
![2015-01-10_14 45 53](https://cloud.githubusercontent.com/assets/6237881/5691441/6f27d998-98d7-11e4-8021-987d376a2dfd.png)

**Comment by CubeWrench202** [comment]
I speak spanish too, lol.

**Comment by MineMaarten** [comment]
This is a server/client desync that causes the client to wait until the server instructs where the (client-sided) item needs to go. The item disappearing basically means a 'time-out'. So no items are actually disappearing from the world, it's just a client thing.
