### ISSUE TITLE
Repeater State isn't saved on SMP

### ISSUE THREAD

**Issue by TheJulianJES** [Qmunity/BluePower#263]
Relatively new custom build version with forge 10.13.2.1277 and minecraft 1.7.10, also sorry for my bad English, I'm German :)
1. Walk away, Repeater is again on 1 tick.
Chunk is all loaded.

**Comment by amadornes** [comment]
Known, already reported and already fixed. Just not pushed to GitHub or CurseForge

**Comment by TheJulianJES** [comment]
@amasornes Sorry ans Thank You!

**Comment by TheJulianJES** [comment]
@amadornes Sorry for the spelling, I'm in my Herman Handy. If I am allowed to ask: When will the fix be uploaded?

**Comment by amadornes** [comment]
I'm not really sure. All the gate renderers have been redone and the logic part is still in the works. Hopefully in less than a week, but who knows... :P

**Comment by TheJulianJES** [comment]
Okay, thank you!

**Comment by TheJulianJES** [comment]
@amadornes Are there new infos on this?

**Comment by amadornes** [comment]
The logic rework is almost done now, I just have to get the Integrated Circuits to work again. Then I'll do some bugfixing of other features I've added in this update and then it'll be released. I can't really give an ETA but I hope it is all done and ready to release this weekend :)

**Comment by TheJulianJES** [comment]
@amadornes I know the hard is work, so thank you ;)

**Comment by TheJulianJES** [comment]
@amadornes New progress :D?

**Comment by amadornes** [comment]
It is already fixed. All the gates but the null cells, and ICs are done by now :)
It's actually going to take me longer than I expected to get everything done, since I'm basically rewriting the wires and the gates. There's also been pretty big changes to the tubes and a few new other features added. All of them are WIP but none of them are actually fully done. I'll try to get two of them finished this weekend so maybe we can release next week. Sorry for the wait :(

**Comment by TheJulianJES** [comment]
@amadornes Thanks! A good mod can take some time! :)

**Comment by Pilad** [comment]
Very cool ))) I waiting fixing version ))
