### ISSUE TITLE
[Suggestion] Storage of Blue Power : Blue Battery

### ISSUE THREAD

**Issue by MrKickkiller** [Qmunity/BluePower#269]
I've been looking trough the repo and I can't seem to find any block that would be used as a battery for Blue Power.

**Comment by TheJulianJES** [comment]
I would like if BluePower Energy ia compatible with RF. Converter?

**Comment by Quetzi** [comment]
It makes absolutely zero sense for the 2 power types to be fully compatible as the applications are quite different. Why would you want it compatible?

**Comment by TheJulianJES** [comment]
So you can use your exisiting power setup.

**Comment by Quetzi** [comment]
You would like to eliminate the gameplay opportunities adding a power system brings, 'just because' ? I was hoping for some reasons to add compatibility beyond laziness/unwillingness ;)

**Comment by TheJulianJES** [comment]
Yeah, probaly a Vetter idea.

**Comment by nanakisan** [comment]
Just thought i'd throw my two cents here. The only reason RP2 had a Blutricity Engine (MJ compatibility) was because people begged Eloraam for it. On it's own Blutricity had a concept of energy transfer that was quite unique. Namely how one could not just use power straight from a kinetic motor. But rather one would have to properly step down the power using a transformer. From there your long range power transfer was accomplished via 10k/Insulated Blutric Wire. ....Quetzi for all that is holy. I hope you plan to give us basalt generators using the thermopiles.

**Comment by TrupJP2** [comment]
Maybe I'm confused but I think I have the latest Bluepower and there are no electricity items in it whatsoever?

**Comment by MoreThanHidden** [comment]
Implemented in newer versions.
