### ISSUE TITLE
(Mostly) Integrated Circuits Bugs

### ISSUE THREAD

**Issue by AppleConnoiseur** [Qmunity/BluePower#275]
__Qmunity Build:__ QmunityLib-1.7.10-0.1.69-universal
__BluePower Build:__ BluePower-1.7.10-0.2.835-universal

Circuits do not take into account the players relative position and rotation when placing down on the plate.
![Wrong placement.](https://dl.dropboxusercontent.com/u/547140/pix2/2015-01-23_11.32.31.png)

Off-center rendering while moving. Probably related to not taking bobbing in account .
![Off-center circuit plate.](https://dl.dropboxusercontent.com/u/547140/pix2/2015-01-23_11.26.06.png)

AND-gate texture not rendering properly when using screwdriver.
![AND-gate](https://dl.dropboxusercontent.com/u/547140/pix2/2015-01-22_19.41.21.png)

Blue stone wires do not work in circuits.
![Blue stone wires](https://dl.dropboxusercontent.com/u/547140/pix2/2015-01-23_11.35.44.png)

Light sensor does not work at all. Outputs signal at all times.

**Comment by amadornes** [comment]
ICs are getting completely rewritten and so are the all the rest of the gates. I'd suggest following all the devs on twitter to get those kinds of news ;)
Here's an album of everything I've done since the beginning of December: http://imgur.com/a/2CELj Some of the features listed there are already in the current version of BluePower, but most of them are new :P

The rendering of the ghost image is something we still haven't figured out how to fix. Bobbing has nothing to do, I've already tested it, but if you get further away from it you'll see it gets centered. Btw, it also happens even if you're not moving :P

**Comment by MineMaarten** [comment]
... and the blue stone wire doesn't work intentionally, it prevents the gate to 'power itself' basically. You can't have a wire right on the input of an IC. Amadornes has plans to rewrite the IC in a gate that will allow a lot more (like actual wires, and no limitation)

**Comment by AppleConnoiseur** [comment]
So the mod will be practically new at that point. I see. Will keep tabs at the Twitter then :P.
