### ISSUE TITLE
Reinforced Sapphire Glass "Render"

### ISSUE THREAD

**Issue by kurokuno** [Qmunity/BluePower#296]
in world its solid you can not see through it and yet in your hand and in NEI its a see through and rather pretty texture

**Comment by GirafiStudios** [comment]
I assume this have something to do with Optifine, not sure tho.

**Comment by amadornes** [comment]
It probably has something to do with either optifine, shaders or some other mod doing rendering wrong. It renders perfectly for everybody else. http://gyazo.com/be1c4135610c401e43913cc556004550

**Comment by kurokuno** [comment]
i guess your right its optifine but sadly i cannot sacrifice an extra 120 FPS for some nice glass...soo i guess we just have to call this one closed  =P as im guessing its unfixable

**Comment by amadornes** [comment]
Well, you can edit the texture in GIMP, Paint.NET or Photoshop and just remove the transparent part, but that would be a pain to do since you would have to edit a ton of textures (needed for the connected textures to work).
Since you want this issue to be closed, I'm going to close it. You can still post comments once it's closed so feel free to let us know if you tried what I said and it worked :)
