### ISSUE TITLE
Z-Fighting on Accelerators

### ISSUE THREAD

**Issue by dninemfive** [Qmunity/BluePower#320]
I presume you have a pneumatic tube inside the accelerator? Its textures clip through the larger model. Wasn't captured well in pictures, but here are some anyway:
![2015-03-10_18 08 52](https://cloud.githubusercontent.com/assets/11084010/6588619/5f7dacb8-c751-11e4-90a0-f70a9e5a51d1.png)
![2015-03-10_18 08 53_3](https://cloud.githubusercontent.com/assets/11084010/6588621/5f827c7a-c751-11e4-987a-5fa276dc9098.png)
![2015-03-10_18 09 22](https://cloud.githubusercontent.com/assets/11084010/6588620/5f816f24-c751-11e4-815a-17d16f950464.png)
Still occurs with a magnetic tube attached:
![2015-03-10_18 09 44](https://cloud.githubusercontent.com/assets/11084010/6588623/5f84b95e-c751-11e4-9491-5f0e2b3b2c80.png)
![2015-03-10_18 09 49](https://cloud.githubusercontent.com/assets/11084010/6588622/5f835492-c751-11e4-9232-a9aacd968a3c.png)

**Comment by amadornes** [comment]
I can confirm this, I also discovered it yesterday. It should be fairly easy to fix. Also, we're going to fix the accelerator rendering so the part that's connected to the magtube looks like an actual magtube instead of a pneumatic tube.
I'll work on it today, it shouldn't take too long to fix it :P
