### ISSUE TITLE
Occasional performance issues with bluestone wire

### ISSUE THREAD

**Issue by Gotolei** [Qmunity/BluePower#340]
https://gfycat.com/UnselfishBouncyBaboon

Doesn't seem to be reliably reproducible except for that specific area unfortunately, not quite sure what's causing it (aside from, uneducated guess, the sudden spam of chunk updates). Nothing is written to the log.
I have some other wiring in the same world that works without problems.

Modpack is Genesis 1.2.1a, mod version is 0.1.766. Can provide world download if needed.

**Comment by amadornes** [comment]
The version of BluePower that you're using was released all the way back in October of last year. We don't support for old versions, but you may want to know that the wires have been rewritten since then and work much better now, so you shouldn't have lag issues anymore.
I hope the pack you're playing updates soon because there have been lots of really big changes since then.

**Note:** I've just talked to Q and he's told me he's been talking to you about it already. I guess it's on Carpenters Blocks' side then?

**Comment by Gotolei** [comment]
I have no idea. Even after updating both bluepower and carpenters it still behaves like this.
