### ISSUE TITLE
Feature Request - Item delete after x seconds

### ISSUE THREAD

**Issue by Tencao** [Qmunity/BluePower#343]
I have a major issue with bluepower mod on my server. So many people incorrectly setup machines by setting the timer too fast, and items loop inside the system. This is incredibly annoying, as there's no way to fix this without manually finding it myself, and by then, the server is already crashing and restarting. If possible, a config option that adds a life time for items in tubes and filters, in seconds would be incredibly useful for both me and other server owners who care about performance.

**Comment by nanakisan** [comment]
Tubes I understand but filters shouldn't also be causing lag? They simply act as a return point if the item they send is not accepted. Also why not use Opis? That should locate the tubes responsible for your servers lag.

**Comment by Tencao** [comment]
We do, but this is presuming the server didn't die from item overload overnight. With project_e been back, and people been able to spam items through blazerod machines, I've seen filters have a backlog of over 600 stacks, pipes probably have the same amount looping inside. Filters probably don't cause as much lag, but just having a config option to clear the item in the backlog if they don't go anywhere after x seconds would be nice for big servers that have to deal with this.

**Comment by Quetzi** [comment]
If you have 600 stacks backstuffed in a filter then your tube network takes about 30 seconds to get from that filter to the furthest macerator, it is a big build that is built badly basically. As server admin it is part of your 'job' to educate your users on how to play and use server resources responsibly, this includes tickrate. The build in question can be easily band-aided by adding a restriction tube and a condenser to catch overflow, or a rebuild to minimise travel time.

Learn to use OPIS, if you users are quite happy to throw up such obvious tps sucking builds like this then they will have other equally bad builds that you will need to find. Explain to your users what the issue is and educate them on how to minimise backstuffing. That whole mechanic is there to ensure items aren't lost, adding a way to introduce item loss as part of the process doesn't make any sense at all.

**Comment by abaw7** [comment]
The issue is that we simply cannot. Ever hear of the term "Idiots will be idiots"? We've tried educating, and limiting it to just users who are educated, we still ended up with problems. A simple solution would be to give an option to remove an item in transit if it has bounced more then X Times. It'd be simple to add an int value to the item's metadata, and keep counting everytime it bounces. If it goes over the configurable limit, delete or do something with it (Possibly throwing it into the world).
