### ISSUE TITLE
Crash with alloy furnace generating recycling recipes

### ISSUE THREAD

**Issue by Xenooom** [Qmunity/BluePower#344]
This is happening when i have engineer's toolbox mod installed, i think it because of compatibility. Already tried with a build with the last changes i built from github.

here's a crash log:

http://pastebin.com/CsGkiQGK

Thanks in advance

**Comment by tsargoth** [comment]
Same issue. 

I attempted blacklisting all the items for the config and either I listed the items wrong or it didn't help.

**Comment by Leguan12** [comment]
Would it be possible just to create a config option to disable the recycling recipes altogether (prevent the mod from trying to generate them) ?
Having the same problem (also tested with the alloy furnace from Project Red, same error here so it seems to be a general problem with anything that generates smelting recipes automatically-there seem to be some recipes that can't be mapped correctly and cause a crash whilst the mod tries to generate the recycling recipes)

**Comment by amadornes** [comment]
I could bet my house that it has something to do with people registering recipes with null items. I've seen this before in other mods.
I thought we already had a way around it so recipes with null items wouldn't get registered, but we are surely going to add a way to disable recycling. I'll talk to @MineMaarten about it, since he's the one who added the Alloy Furnace and he'll be able to work around his code a bit more easily than I would :P

**Comment by MoreThanHidden** [comment]
Issue resolved in the 1.12 version.
