### ISSUE TITLE
Bluestone Repeater Reset

### ISSUE THREAD

**Issue by westloar** [Qmunity/BluePower#350]
I am running an FTB Dark Trilogy server and the bluestone repeaters I have placed seem to reset themselves.

This appears to be happening whenever I log out and then back in (i.e. area becomes unloaded). This breaks a Factory Manager set-up by messing up the timings of certain machines.

Is this a known bug and are there any fixes?

**Comment by amadornes** [comment]
This was a bug waaaay back before the gates and wires were rewritten and I thought I fixed it when I rewrote them. I'll check and see if I can reproduce it, though I'm pretty sure I also checked at the time

**Comment by amadornes** [comment]
I cannot seem to be able to reproduce it in my dev environment. What versions of BP and QL are you using?

**Comment by westloar** [comment]
Blue Power Version: 1.7.10- 0.2.835
QL: 1.7.10-1.69

**Comment by amadornes** [comment]
Wow, you're using some really ancient versions of both BP and QL... And it looks like they were released before that bug was fixed :/
I can't do much about it other than poking @tfox83 and asking him to update the pack. You could also update it yourself if you want. There's been tons of bugfixes since those versions got released so it'd probably be good to update even if the pack doesn't :P

**Comment by westloar** [comment]
Ah ok, no worries, that would explain this then, thanks for your help :+1:
