### ISSUE TITLE
Bug/feature of bluepower timer

### ISSUE THREAD

**Issue by Viperwow** [Qmunity/BluePower#377]
Hello, don't know is it a bug or how really works bluepower timer, but if I tried to connect it to pneumatic tube directly it gives only one tick, then timer get back signal and get constant signal for input and output on a same wire.
The situation repeats itself with bluepower repeater, but not with original redstone repeater! It gives me  ticking of timer without affecting timer.

**Comment by abalabahaha** [comment]
Screenshot?

**Comment by Viperwow** [comment]
Screenshot (not updated for the newest version of BP): http://i.imgur.com/0Y9fJX6.png
From left to right:
1) ticking, wire cannot be connected to original redstone
2) connected and ticking without recieving back a constant signal
3) connected, only 1 tick and constant signal as a result
4) ticking(by the way no output signal at all may be), cannot be connected to a tube

**Comment by amadornes** [comment]
The way you are supposed to do this is like in the 4th case, but with a freestanding wire in the same blockspace as the normal wire. It'll then connect to both the tube and the other wire allowing them to share power :)
Wires powering redstone and redstone powering wires is something we've always tried to avoid and that should be fixed in the next update :)
