### ISSUE TITLE
Project Table Crash

### ISSUE THREAD

**Issue by ghost** [Qmunity/BluePower#394]
Crash Report: http://pastebin.com/rN66hAyT

**Comment by amadornes** [comment]
This issue seems to be caused by Redstonic and not BluePower. It does happen when you interact with Project Tables, but it seems to be on Raizunne's end and not on ours. Probably a recipe with a null item or something like that. I can't help with this, but it'd be good to bring Raizunne into the conversation and see what he/she can say about this :)

**Comment by FrenzyFire000** [comment]
I am crashing on the project table as well, but no mention of Redstonic on my crash report. I have had to remove my technic legends twice and reinstall it to get it to work again. This last time it happened I reinstalled and created a new world with nothing in it and placed a project table and it crashed as soon as I placed it.
https://github.com/FrenzyFire000/project-table-crash/new/master?readme=1

**Comment by MoreThanHidden** [comment]
No longer an issue in newer versions
