### ISSUE TITLE
Auto Project Table - High Resource Utilization, even if not processing items

### ISSUE THREAD

**Issue by Dlur100** [Qmunity/BluePower#415]
We have noticed that Auto Project Tables consume a very high amount of CPU time on our server to the point where having even 10 of them in the game will significantly reduce our TPS.  This might be reasonable if all of the crafting tables were processing recipes, but we've found that the most resource intense Auto Project Tables are ones that are just placed in the world, connected to a conduit (generally EnderIO, but also hoppers), but with no items in the inventory.  The auto project tables haven't been banned, but everyone has been discouraged from using them and most players have now removed them from their bases.  This is a shame, because it's a great item that I'd love to use!

Modpack is InfiTech2 3.1.14.  BluePower version is 0.2.962.  This is on the official IT2 public server located at http://infitech.enjin.com/home.  I can request more information from Malfal or Groveham if needed.

**Comment by JasonMcRay** [comment]
Am I safe to assume... Blue Power is not going to be maintained anymore? This issue is easy to recreate. just put Auto Project Table on top of a Hopper and boom. Here is self exlaining screenshot from Opis
![bpprojkect table](https://cloud.githubusercontent.com/assets/4236895/10866555/001eee84-8034-11e5-8d5e-d5831babf829.png)

**Comment by amadornes** [comment]
It is still being maintained. I'm working on it behind the scenes, working on a huge update. I've been pretty busy for the past couple of months so that's why you haven't seen any activity on the repo, but I have more free time now so I'll hopefully be able to make everything work just as it should as soon as possible.
In case you're curious, this update I'm working on is the "Modular Update", which consists on restructuring BP into different modules so that they can be enabled and disabled by the end user. Seeing some of the issues people have been having, I've decided to not just work on restructuring it, but also rewriting and optimising whatever needs some work.
I'm looking into pushing the current changes to the NewQL branch today so people can follow the development of this update. What's in, works, but there's a lot of stuff that's missing (tubes, wiring/logic, power...) so don't expect it to be fully functional.
Anyway, I'll be looking into this as soon as I start porting the Auto Project Table, which should be fairly soon :)

**Comment by MoreThanHidden** [comment]
Should no longer be an issue on modern versions.
