### ISSUE TITLE
Placing Freestanding Bundled Red Alloy Wire Crashes Server

### ISSUE THREAD

**Issue by Rob5Underscores-zz** [Qmunity/BluePower#422]
Placing the wire as shown here (more precisely the wire in the crosshairs): https://gyazo.com/bbf72332f793cb3ee0328758426791a0 causes the server to crash immediately with the following crash-report: http://pastebin.com/Ad7zYQMJ

Thanks

**Comment by empiricist** [comment]
I also ran into this problem and I was able to replicate it with only BluePower installed.  It happens when a bundled cable is placed so that a bundled device like an RGB lamp is connected to cables (with at least one channel powered) on multiple sides.  A screenshot of my setup is [here](https://imgur.com/vlqn7tb).  When a cable is placed where I am currently looking, the game will crash.  The crash log is [here](https://paste.ee/p/D9wIE).

**Comment by Robotia** [comment]
@empiricist Tekkit Legends?

**Comment by empiricist** [comment]
@Robotia I'm not sure what you mean.  The crash seems to happen with just BluePower 0.2.962 installed, no modpacks required.

**Comment by Robotia** [comment]
Just wondering what pack you are using

**Comment by Robotia** [comment]
BluePower is no longer maintained by @Quetzi. Interestingly though, the guy is very active on Twitter. I wish he would at least say that he doesn't have the time :(

You can check out my repository of BluePower (https://github.com/Robotia/BluePower) which has some dupe glitch fixes in it.

**Comment by empiricist** [comment]
Oh, right.  I actually ran into the bug while I was trying to fix a bug with BluePower integration for [RedControls](https://github.com/empiricist/redcontrols).  The game kept crashing when I tried to test my bundled blocks in a certain way, and eventually I realized the same thing happened with just BluePower.

**Comment by MoreThanHidden** [comment]
No longer an issue in latest versions please see #466 for WIP
