### ISSUE TITLE
Freestanding bundled cables connecting

### ISSUE THREAD

**Issue by aleaksah** [Qmunity/BluePower#449]
Freestanding bundled cables always connecting, even they have different colour.

**Comment by MarkL4YG** [comment]
I can confirm a similar issue in Tekkit-Legends:
Whenever I separate two bundled red alloy wires (e.g. using covers, strips or panels) it seems like they're logically still connected.
BUT: There's more: Not only does e.g. the red signal share it's state between those separated lines, the server starts spamming Stack Overflow Exceptions, after a few seconds the "buggy" output starts to flicker and clients within the same chunk get disconnected due to an "internal server error"

**Comment by MoreThanHidden** [comment]
See WIP Items here #466
