### ISSUE TITLE
[1.16.3] Need to update for forge changes - java.lang.IllegalStateException: Can not register to a locked registry. Modder should use Forge Register methods.

### ISSUE THREAD

**Issue by ProsperCraft** [Qmunity/BluePower#569]
### Full Log and Crashlog on pastebin/gist ###
Latest Log-
https://gist.github.com/ProsperCraft/2cf3052961769ec2560645c13b8f95f3
Crash log-
https://gist.github.com/ProsperCraft/67a8093595923fe4935526475f032560

### Forge and Minecraft version ###
Forge: forge-34.1.29
Minecraft 1.16.3

**Comment by YOYOK9** [comment]
Can confirm, I am having the same issue, After some testing It seems after forge 
34.1.26 either crashes on boot (different mod reason no issue after .27 though) and .27 crashes due to bluepower. 
Forge:  forge-34.1.35
MC: 1.16.3
BluePower: 1.16.3-0.5.219-alpha-universal

My logs:
Latest: https://pastebin.com/MgCSKQkY
Crash: https://pastebin.com/DvyZ7hwN

**Comment by MoreThanHidden** [comment]
No worries working on it, have been waiting on a stable release.

**Comment by MoreThanHidden** [comment]
Done 
![image](https://user-images.githubusercontent.com/1351964/97709028-a9ea9e80-1af4-11eb-8fbb-4302710d364b.png)
